<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MassTransit.RabbitMQ" Version="8.3.6" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\fcg-shared-events\src\FCG.Shared.Events\FCG.Shared.Events.csproj" />
  </ItemGroup>

</Project>
